[pytest]
pythonpath = .
testpaths = tests
filterwarnings =
    error:Using `httpx` with `starlette.testclient` is deprecated:starlette.exceptions.StarletteDeprecationWarning
    error:The anyio.abc.BlockingPortal alias is deprecated:DeprecationWarning
