"""Central settings. No magic numbers in route or simulation code."""

SERVICE_NAME = "BI_Town"
VERSION = "0.1.0"

SIMULATION_TICK_SECONDS = 1.0
GAME_MINUTES_PER_TICK = 1
SIMULATION_LOOP_ENABLED = True

INITIAL_DAY = 1
INITIAL_TIME = "08:00"

AGENT_SPEED_PER_TICK = 50.0
ARRIVAL_DISTANCE_THRESHOLD = 10.0
MAX_WORLD_EVENTS = 50
